### PR TITLE
fix cppcheck error

### PR DESCRIPTION
**Pull request by nfer**
> [In C++, wchar_t is a distinct fundamental type](http://www.cplusplus.com/reference/cwchar/wchar_t/)

as it's a fundamental type but not a class, here should use malloc/free but not new/delete.

### CODE REVIEW

**Comment by MJPA** [comment]
From everything I can find, the suggestion is to use "new" in C++ every time over malloc(). Do you have something that says otherwise?

**Comment by nfer** [comment]
```
$ cppcheck . -q
[src/demo/win-main.cpp:94]: (error) Mismatching allocation and deallocation: text
```

**Comment by nfer** [comment]
I found it, the right way to fix cppcheck error is:
```
delete[] text;
```
http://stackoverflow.com/questions/184537/in-what-cases-do-i-use-malloc-vs-new

**Comment by MJPA** [comment]
Committed the `delete []text;` way instead as you can see above, thanks for reporting this.

**Pull request closed without merging**
